### ISSUE TITLE
Consider to move vertical sizing calculated in JS to one that configured in CSS.

### ISSUE THREAD

**Issue by alexeykomov** [reflectcal/reflectcal#70]
Instead of calculating all-day grid container height and main grid container height.

``` css
.all-day-grid-container {
  height: Xpx;
  max-height: 50%;
}
```

``` css
.main-day-grid-container {
  height: calc(100% - Xpx);
  min-height: 50%;
}
```
